// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbwzazycfgmnkqojkgnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJid3phenljZmdtbmtxb2prZ25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MzAyMDIsImV4cCI6MjA3NDUwNjIwMn0.x7u4Nla5lRGygsjhAq4wDdF1_kmgO6mDm6EtV51ZtVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});